services:
  - type: web
    name: tuinue-wasichana-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn --chdir backend run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tuinue-wasichana-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
    autoDeploy: true

  - type: web
    name: tuinue-wasichana-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    autoDeploy: true

databases:
  - name: tuinue-wasichana-db
    databaseName: tuinue_wasichana
    user: dbadmin
    region: oregon
    plan: free